[package]
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axplat-aarch64-dyn"
repository.workspace = true
version = "0.1.0"

[features]
fp-simd = ["axcpu/fp-simd"]
smp = ["axplat/smp"]

[dependencies]
aarch64-cpu = "10"
any-uart = "0.2.11"
axconfig-macros = "0.2"
axcpu = {workspace = true}
axplat = {workspace = true, features = ["irq"]}
fdt-parser = "0.4"
heapless = "0.8"
log = "0.4"
memory_addr = "0.3"
pie-boot = {version = "0.2.9"}
rdrive = "0.15"
smccc = "0.2"
spin = "0.10"
lazyinit = "0.2"