[package]
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axplat-aarch64-dyn"
repository.workspace = true
version = "0.1.0"

[dependencies]
axconfig-macros = "0.2"
axplat = {git = "https://github.com/arceos-org/axplat_crates"}
pie-boot = {version = "0.1.11"}
